spring.application.name=auth-service-api
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_service_api
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=0123456789012345678901234567890123456789012345678901234567890123
jwt.expiration=3600000
